<a href="https://colab.research.google.com/github/sod-04/LABORATORIOS_TALENTO-TECH/blob/main/Laboratorio_7_SDOD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Parte 1

In [ ]:
#Creación de DataFrame con el nombre, profesión y país de 10 personas

import pandas as pd

data = {
  'Nombre': ['Ana', 'Carlos', 'Sophia', 'Noah', 'Emma', 'Juana', 'Camilo', 'Antonio'],
  'Profesion': ['Ingeniera', 'Médico', 'Diseñadora', 'Arquitecto', 'Abogada', 'Periodista', 'Empresario', 'Profesor'],
  'Pais': ['México', 'Argentina', 'Estados Unidos', 'Canadá', 'Nueva Zelanda', 'España', 'Colombia', 'Chile']
}

df = pd.DataFrame (data)
print(df)


    Nombre   Profesion            Pais
0      Ana   Ingeniera          México
1   Carlos      Médico       Argentina
2   Sophia  Diseñadora  Estados Unidos
3     Noah  Arquitecto          Canadá
4     Emma     Abogada   Nueva Zelanda
5    Juana  Periodista          España
6   Camilo  Empresario        Colombia
7  Antonio    Profesor           Chile


In [3]:
#Carga de un archivo CSV

import pandas as pd

#Cargar el archivo CSV
df = pd.read_csv('data.csv')

#Mostrar las 5 primeras filas del DataFrame
print(df.head())

   Duracion  Pulso  Maxpulso  Calorias
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


In [ ]:
#DataFrame con 100 filas y 8 columnas aleatorias

import pandas as pd
import numpy as np
print(np)
df = pd.DataFrame (np.random.randn(100, 8))
print(df.describe())

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>
                0           1           2           3           4           5  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.027538    0.105077    0.019476   -0.033440   -0.040977   -0.244564   
std      0.897934    1.105932    0.959472    0.896937    1.004736    1.032025   
min     -2.020607   -3.248576   -2.648812   -2.594521   -2.746259   -3.077017   
25%     -0.691287   -0.597460   -0.726401   -0.686862   -0.781556   -0.913077   
50%      0.096241    0.244043   -0.063900    0.016381    0.079445   -0.264818   
75%      0.566358    0.741001    0.667478    0.509284    0.731910    0.463761   
max      2.373552    2.680627    2.368358    1.979121    2.387295    2.687679   

                6           7  
count  100.000000  100.000000  
mean    -0.072454    0.227404  
std      1.000780    0.923822  
min     -2.878697   -2.666018  
25%     -0.763218   -0.30688

#Parte 2

In [ ]:
#Array de números del 1 al 10, mostrando la suma, la media y el valor máximo

import numpy as np
arr = np.arange(1, 11)
print('Array:', arr)
print('Suma:', arr.sum())
print('Media:', arr.mean())
print('Máximo:', arr.max())


Array: [ 1  2  3  4  5  6  7  8  9 10]
Suma: 55
Media: 5.5
Máximo: 10


In [ ]:
#Array de 3x4, lleno de ceros y array redimensionado de 2x6

import numpy as np
arr = np.zeros((3,4))
print('Array original (3x4):')
print(arr)
print()

#Cambiar forma
arr_reshaped = arr.reshape((2,6))
print('Array redimensionado (2x6):')
print(arr_reshaped)

Array original (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array redimensionado (2x6):
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
#Matriz aleatoria de 3x3 y su transpuesta

import numpy as np
arr = np.random.rand(3,3)
print('Matriz original:')
print(arr)
print()

#Calcular la transpuesta
arr_transpuesta = arr.T
print('Matriz transpuesta:')
print(arr_transpuesta)


Matriz original:
[[0.778234   0.2662372  0.14941602]
 [0.69925377 0.93853742 0.39682493]
 [0.44093519 0.27433925 0.9931884 ]]

Matriz transpuesta:
[[0.778234   0.69925377 0.44093519]
 [0.2662372  0.93853742 0.27433925]
 [0.14941602 0.39682493 0.9931884 ]]


In [ ]:
#Concatenar dos arrays de NumPy

import numpy as np
import pandas as pd
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
array_concatenado = np.concatenate((a, b))
print('Array concatenado:', array_concatenado)

Array concatenado: [ 1  2  3  4  5  6  7  8  9 10]
